### show
GET http://localhost:8080/sample/100
    ?param1=2
X-Api-Key: my key 1

### list
GET http://localhost:8080/sample/

### list flow
GET http://localhost:8080/sample/v2

### update
PUT http://localhost:8080/sample/200
Content-Type: application/json

 {
    "id": 100,
    "name": "user 100",
    "email": null
 }

### create
POST http://localhost:8080/sample
Content-Type: application/json

{
    "id": 201,
    "name": "user 201",
    "email": "201@example.com"
}

### delete
DELETE http://localhost:8080/sample/100
