/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package name.stepin.client.petstore.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param id
 * @param name
 */

data class Category(
    @field:JsonProperty("id")
    val id: Long? = null,
    @field:JsonProperty("name")
    val name: String? = null,
)
