/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package name.stepin.client.petstore.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param id
 * @param petId
 * @param quantity
 * @param shipDate
 * @param status Order Status
 * @param complete
 */

data class Order(
    @field:JsonProperty("id")
    val id: Long? = null,
    @field:JsonProperty("petId")
    val petId: Long? = null,
    @field:JsonProperty("quantity")
    val quantity: Int? = null,
    @field:JsonProperty("shipDate")
    val shipDate: java.time.OffsetDateTime? = null,
    // Order Status
    @field:JsonProperty("status")
    val status: Order.Status? = null,
    @field:JsonProperty("complete")
    val complete: Boolean? = null,
) {
    /**
     * Order Status
     *
     * Values: PLACED,APPROVED,DELIVERED
     */
    enum class Status(
        val value: String,
    ) {
        @JsonProperty(value = "placed")
        PLACED("placed"),

        @JsonProperty(value = "approved")
        APPROVED("approved"),

        @JsonProperty(value = "delivered")
        DELIVERED("delivered"),
    }
}
