/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package name.stepin.client.petstore.models

import com.fasterxml.jackson.annotation.JsonProperty
import name.stepin.client.petstore.models.Category
import name.stepin.client.petstore.models.Tag

/**
 *
 *
 * @param name
 * @param photoUrls
 * @param id
 * @param category
 * @param tags
 * @param status pet status in the store
 */

data class Pet(
    @field:JsonProperty("name")
    val name: String,
    @field:JsonProperty("photoUrls")
    val photoUrls: List<String>,
    @field:JsonProperty("id")
    val id: Long? = null,
    @field:JsonProperty("category")
    val category: Category? = null,
    @field:JsonProperty("tags")
    val tags: List<Tag>? = null,
    // pet status in the store
    @field:JsonProperty("status")
    val status: Pet.Status? = null,
) {
    /**
     * pet status in the store
     *
     * Values: AVAILABLE,PENDING,SOLD
     */
    enum class Status(
        val value: String,
    ) {
        @JsonProperty(value = "available")
        AVAILABLE("available"),

        @JsonProperty(value = "pending")
        PENDING("pending"),

        @JsonProperty(value = "sold")
        SOLD("sold"),
    }
}
