/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport",
)

package name.stepin.client.petstore.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param id
 * @param username
 * @param firstName
 * @param lastName
 * @param email
 * @param password
 * @param phone
 * @param userStatus User Status
 */

data class User(
    @field:JsonProperty("id")
    val id: Long? = null,
    @field:JsonProperty("username")
    val username: String? = null,
    @field:JsonProperty("firstName")
    val firstName: String? = null,
    @field:JsonProperty("lastName")
    val lastName: String? = null,
    @field:JsonProperty("email")
    val email: String? = null,
    @field:JsonProperty("password")
    val password: String? = null,
    @field:JsonProperty("phone")
    val phone: String? = null,
    // User Status
    @field:JsonProperty("userStatus")
    val userStatus: Int? = null,
)
